# Generated by Django 3.2 on 2021-06-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='wishlist',
            field=models.JSONField(default=dict),
        ),
    ]
