# Generated by Django 3.2 on 2021-06-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_users_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sellerid',
            field=models.IntegerField(default=0),
        ),
    ]
